/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TradeResult = IDL.Record({
  'duration' : IDL.Nat,
  'pnlPercent' : IDL.Float64,
  'signalId' : IDL.Nat,
  'pnlPips' : IDL.Float64,
  'timestamp' : IDL.Int,
  'entryPrice' : IDL.Float64,
  'exitPrice' : IDL.Float64,
  'outcome' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TradingSignal = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'direction' : IDL.Text,
  'tradeType' : IDL.Text,
  'confidenceScore' : IDL.Nat,
  'rrRatio' : IDL.Float64,
  'stopLoss' : IDL.Float64,
  'timestamp' : IDL.Int,
  'entryPrice' : IDL.Float64,
  'takeProfit1' : IDL.Float64,
  'takeProfit2' : IDL.Float64,
  'takeProfit3' : IDL.Float64,
  'aiReasoning' : IDL.Text,
  'strategyTags' : IDL.Vec(IDL.Text),
  'symbol' : IDL.Text,
});
export const BacktestResult = IDL.Record({
  'id' : IDL.Nat,
  'totalTrades' : IDL.Nat,
  'endDate' : IDL.Int,
  'sharpeRatio' : IDL.Float64,
  'resultsJSON' : IDL.Text,
  'winRate' : IDL.Float64,
  'strategyName' : IDL.Text,
  'maxDrawdown' : IDL.Float64,
  'profitFactor' : IDL.Float64,
  'startDate' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PriceCache = IDL.Record({
  'timestamp' : IDL.Int,
  'price' : IDL.Float64,
});
export const UserSettings = IDL.Record({
  'maxDailyTrades' : IDL.Nat,
  'notificationsEnabled' : IDL.Bool,
  'preferredTimeframe' : IDL.Text,
  'riskPercentage' : IDL.Float64,
  'autoTrade' : IDL.Bool,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTradeResult' : IDL.Func([TradeResult], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSignal' : IDL.Func([TradingSignal], [IDL.Nat], []),
  'deleteSignal' : IDL.Func([IDL.Nat], [], []),
  'getActiveSignals' : IDL.Func([], [IDL.Vec(TradingSignal)], ['query']),
  'getAllSignals' : IDL.Func([], [IDL.Vec(TradingSignal)], ['query']),
  'getBacktestResults' : IDL.Func([], [IDL.Vec(BacktestResult)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPriceCache' : IDL.Func([], [IDL.Opt(PriceCache)], ['query']),
  'getSignal' : IDL.Func([IDL.Nat], [IDL.Opt(TradingSignal)], ['query']),
  'getTradeHistory' : IDL.Func([], [IDL.Vec(TradeResult)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSettings' : IDL.Func([], [UserSettings], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'refreshPrice' : IDL.Func([], [IDL.Float64], []),
  'saveBacktestResult' : IDL.Func([BacktestResult], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateSignalStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateUserSettings' : IDL.Func([UserSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TradeResult = IDL.Record({
    'duration' : IDL.Nat,
    'pnlPercent' : IDL.Float64,
    'signalId' : IDL.Nat,
    'pnlPips' : IDL.Float64,
    'timestamp' : IDL.Int,
    'entryPrice' : IDL.Float64,
    'exitPrice' : IDL.Float64,
    'outcome' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TradingSignal = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'direction' : IDL.Text,
    'tradeType' : IDL.Text,
    'confidenceScore' : IDL.Nat,
    'rrRatio' : IDL.Float64,
    'stopLoss' : IDL.Float64,
    'timestamp' : IDL.Int,
    'entryPrice' : IDL.Float64,
    'takeProfit1' : IDL.Float64,
    'takeProfit2' : IDL.Float64,
    'takeProfit3' : IDL.Float64,
    'aiReasoning' : IDL.Text,
    'strategyTags' : IDL.Vec(IDL.Text),
    'symbol' : IDL.Text,
  });
  const BacktestResult = IDL.Record({
    'id' : IDL.Nat,
    'totalTrades' : IDL.Nat,
    'endDate' : IDL.Int,
    'sharpeRatio' : IDL.Float64,
    'resultsJSON' : IDL.Text,
    'winRate' : IDL.Float64,
    'strategyName' : IDL.Text,
    'maxDrawdown' : IDL.Float64,
    'profitFactor' : IDL.Float64,
    'startDate' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PriceCache = IDL.Record({
    'timestamp' : IDL.Int,
    'price' : IDL.Float64,
  });
  const UserSettings = IDL.Record({
    'maxDailyTrades' : IDL.Nat,
    'notificationsEnabled' : IDL.Bool,
    'preferredTimeframe' : IDL.Text,
    'riskPercentage' : IDL.Float64,
    'autoTrade' : IDL.Bool,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTradeResult' : IDL.Func([TradeResult], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSignal' : IDL.Func([TradingSignal], [IDL.Nat], []),
    'deleteSignal' : IDL.Func([IDL.Nat], [], []),
    'getActiveSignals' : IDL.Func([], [IDL.Vec(TradingSignal)], ['query']),
    'getAllSignals' : IDL.Func([], [IDL.Vec(TradingSignal)], ['query']),
    'getBacktestResults' : IDL.Func([], [IDL.Vec(BacktestResult)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPriceCache' : IDL.Func([], [IDL.Opt(PriceCache)], ['query']),
    'getSignal' : IDL.Func([IDL.Nat], [IDL.Opt(TradingSignal)], ['query']),
    'getTradeHistory' : IDL.Func([], [IDL.Vec(TradeResult)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSettings' : IDL.Func([], [UserSettings], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'refreshPrice' : IDL.Func([], [IDL.Float64], []),
    'saveBacktestResult' : IDL.Func([BacktestResult], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateSignalStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateUserSettings' : IDL.Func([UserSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };