/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BacktestResult {
  'id' : bigint,
  'totalTrades' : bigint,
  'endDate' : bigint,
  'sharpeRatio' : number,
  'resultsJSON' : string,
  'winRate' : number,
  'strategyName' : string,
  'maxDrawdown' : number,
  'profitFactor' : number,
  'startDate' : bigint,
}
export interface PriceCache { 'timestamp' : bigint, 'price' : number }
export interface TradeResult {
  'duration' : bigint,
  'pnlPercent' : number,
  'signalId' : bigint,
  'pnlPips' : number,
  'timestamp' : bigint,
  'entryPrice' : number,
  'exitPrice' : number,
  'outcome' : string,
}
export interface TradingSignal {
  'id' : bigint,
  'status' : string,
  'direction' : string,
  'tradeType' : string,
  'confidenceScore' : bigint,
  'rrRatio' : number,
  'stopLoss' : number,
  'timestamp' : bigint,
  'entryPrice' : number,
  'takeProfit1' : number,
  'takeProfit2' : number,
  'takeProfit3' : number,
  'aiReasoning' : string,
  'strategyTags' : Array<string>,
  'symbol' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSettings {
  'maxDailyTrades' : bigint,
  'notificationsEnabled' : boolean,
  'preferredTimeframe' : string,
  'riskPercentage' : number,
  'autoTrade' : boolean,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTradeResult' : ActorMethod<[TradeResult], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSignal' : ActorMethod<[TradingSignal], bigint>,
  'deleteSignal' : ActorMethod<[bigint], undefined>,
  'getActiveSignals' : ActorMethod<[], Array<TradingSignal>>,
  'getAllSignals' : ActorMethod<[], Array<TradingSignal>>,
  'getBacktestResults' : ActorMethod<[], Array<BacktestResult>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPriceCache' : ActorMethod<[], [] | [PriceCache]>,
  'getSignal' : ActorMethod<[bigint], [] | [TradingSignal]>,
  'getTradeHistory' : ActorMethod<[], Array<TradeResult>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSettings' : ActorMethod<[], UserSettings>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'refreshPrice' : ActorMethod<[], number>,
  'saveBacktestResult' : ActorMethod<[BacktestResult], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateSignalStatus' : ActorMethod<[bigint, string], undefined>,
  'updateUserSettings' : ActorMethod<[UserSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];